FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

TARGET_CFLAGS += " -DIOTCONNECT_CPID='\"avtds\"' "
TARGET_CFLAGS += " -DIOTCONNECT_ENV='\"avnetpoc\"' "
TARGET_CFLAGS += " -DIOTCONNECT_DUID='\"linuxDemo\"' "
TARGET_CFLAGS += " -DIOTCONNECT_SYMMETRIC_KEY='\"MDEyMzQ1Njc4OWFiY2RlZg==\"' "
